# Generated by Django 4.2.6 on 2024-01-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_medicine_expiry_alter_medicine_manufacturing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturing',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
